language: node_js

sudo: true

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install tesseract-ocr-eng
  - sudo apt-get install tesseract-ocr-hun
  - which tesseract
  - tesseract -h

node_js:
#  - "8"
#  - "7"
#  - "6"
#  - "5"
  - "4"
