language: node_js

sudo: true

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install tesseract-ocr tesseract-ocr-eng tesseract-ocr-hun
  - tesseract --list-langs

node_js:
  - "8"
  - "7"
  - "6"
  - "5"
  - "4"
